# Generated by Django 4.1.1 on 2022-09-28 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdOrder', models.IntegerField(blank=True, null=True)),
                ('Option_dep', models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved'), ('rejection', 'rejection')], default='pending', max_length=50, null=True)),
                ('Path', models.CharField(blank=True, max_length=100, null=True)),
                ('NumJob', models.IntegerField(blank=True, null=True)),
                ('NameUser', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.BooleanField(blank=True, default=False, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Username', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 29, 0, 42, 33, 893240))),
            ],
        ),
        migrations.DeleteModel(
            name='Section_Options',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Path_Doctor',
        ),
        migrations.RemoveField(
            model_name='nursing',
            name='Path_Nursing',
        ),
        migrations.AddField(
            model_name='doctor',
            name='IdOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='NameUser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='NumJob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='State',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 29, 0, 42, 33, 893240)),
        ),
        migrations.AddField(
            model_name='employee_form',
            name='FinalStat',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee_form',
            name='classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nursing',
            name='IdOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursing',
            name='NameUser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nursing',
            name='Notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursing',
            name='NumJob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursing',
            name='Path',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nursing',
            name='State',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='nursing',
            name='Username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nursing',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 29, 0, 42, 33, 893240)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Option_dep',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved'), ('rejection', 'rejection')], default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_form',
            name='Job_Title',
            field=models.CharField(blank=True, choices=[('Administrative Departments الأقسام الأدارية', (('اداري', 'اداري'), ('Specialist اخصائي اداري', 'Specialist اخصائي اداري'))), (' Medical Departments الأقسام الطبية ', (('Specialist اخصائي طبيب', 'Specialist اخصائي طبيب'), ('Consultant استشاري', 'Consultant استشاري'), ('Resident مقيم', 'Resident مقيم'))), ('Nursing Departments أقسام التمريض', (('Specialist Nurse اخصائي تمريض', 'Specialist Nurse اخصائي تمريض'),))], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_form',
            name='Start_Date',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 29)),
        ),
        migrations.AlterField(
            model_name='employee_form',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 29, 0, 42, 33, 893240)),
        ),
        migrations.AlterField(
            model_name='employee_form',
            name='end_Date',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 29)),
        ),
        migrations.AlterField(
            model_name='nursing',
            name='Option_dep',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved'), ('rejection', 'rejection')], default='pending', max_length=50, null=True),
        ),
    ]
