# Generated by Django 4.1.2 on 2022-10-12 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0016_alter_administrator_created_alter_doctor_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 12, 35, 37, 411544)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 12, 35, 37, 409559)),
        ),
        migrations.AlterField(
            model_name='employee_form',
            name='Start_Date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 12)),
        ),
        migrations.AlterField(
            model_name='employee_form',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 12, 35, 37, 405574)),
        ),
        migrations.AlterField(
            model_name='employee_form',
            name='end_Date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 12)),
        ),
        migrations.AlterField(
            model_name='nursing',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 12, 35, 37, 408562)),
        ),
    ]
