# Generated by Django 4.1 on 2022-10-11 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em', '0020_alter_administrator_created_alter_doctor_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 8, 32, 52, 446440)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 8, 32, 52, 446440)),
        ),
        migrations.AlterField(
            model_name='employee_form',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 8, 32, 52, 430813)),
        ),
        migrations.AlterField(
            model_name='nursing',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 8, 32, 52, 446440)),
        ),
    ]
